### ISSUE TITLE
failed to fetch  glue.wasm in node_modules

### ISSUE THREAD

**Issue by jude90** [ceifa/demoon#2]
![image](https://user-images.githubusercontent.com/2552029/205085422-4bf48bf6-a9d8-4495-8974-2ea304fe3ab0.png)
OS: 
Linux VM-0-4-centos 4.18.0-348.7.1.el8_5.x86_64 #1
Node.js v18.12.1
demoon : "version": "0.0.8"
wasmoon : "1.12.1"

**Comment by ceifa** [comment]
This is a problem that happen on Node 18. The solution is just update the wasmoon package. Will do it later.

**Comment by ceifa** [comment]
Fixed
